name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"
      - name: Backend Tests
        working-directory: ./backend
        run: |
          pip install -r requirements.txt pytest
          pytest -v
          
      - name: Check Python with ruff
        run: |
          python3 -m pip install --upgrade pip
          pip install ruff
          ruff check backend/
      
      - name: Frontend Tests
        working-directory: ./frontend
        run: |
          npm ci 
          npx tsc --noEmit
          npm run lint
      

      - name: Test Docker Build
        run: docker build -t movie-picker .
